ode {
    stage ("SCM"){
        git 'https://github.com/sandeepyarramshetty/spring-petclinic.git'
    }
    stage ("Build the package"){
        sh label: '', script: 'mvn package'
    }
    stage ("Test results"){
        junit 'target/surefire-reports/*.xml'
    }
    stage ("archival"){
        archiveArtifacts 'target/*.jar'
    }

}